package com.example.capstonandroid.network.dto

data class Data(
    val altitude: Int,
    val average_speed: Double,
    val calorie: Double,
    val comment: List<Comment>,
    val content: String,
    val created_at: String,
    val date: String,
    val distance: Double,
    val event: String,
    val gpsData: GpsData,
    val gps_id: String,
    val id: Int,
    val img: Any,
    val kind: String,
    val likes: List<Any>,
    val mmr: Int,
    val opponent_id: Any,
    val range: String,
    val time: Int,
    val title: String,
    val track_id: Any,
    val updated_at: String,
    val user: User,
    val user_id: Int)